name: Build_mkworld

on: 
  #release:
  #  types: [published]

  #push:
  #  branches: 
  #    - master
  #  tags:
  #    - v1.*

  #schedule:
  #  - cron: 0 8 * * 5
  
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: initenv
      uses: actions/checkout@master
    
    - name: build world.bin
      #working-directory: ./attic/world
      run: |
        gcc -v 
        uname -a
        cd attic/world/
        source ./build.sh
        ./mkworld
      
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: worldbin
        path: attic/world/
